import { LwColor } from "../types";

export const avatarBorderColor: Record<LwColor, string> = {
    amber: "ring-2 ring-offset-2 ring-amber-400",
    blue: "ring-2 ring-offset-2 ring-blue-400",
    cyan: "ring-2 ring-offset-2 ring-cyan-400",
    emerald: "ring-2 ring-offset-2 ring-emerald-400",
    fuchsia: "ring-2 ring-offset-2 ring-fuchsia-400",
    gray: "ring-2 ring-offset-2 ring-gray-400",
    green: "ring-2 ring-offset-2 ring-green-400",
    indigo: "ring-2 ring-offset-2 ring-indigo-400",
    lime: "ring-2 ring-offset-2 ring-lime-400",
    neutral: "ring-2 ring-offset-2 ring-neutral-400",
    orange: "ring-2 ring-offset-2 ring-orange-400",
    pink: "ring-2 ring-offset-2 ring-pink-400",
    purple: "ring-2 ring-offset-2 ring-purple-400",
    red: "ring-2 ring-offset-2 ring-red-400",
    rose: "ring-2 ring-offset-2 ring-rose-400",
    sky: "ring-2 ring-offset-2 ring-sky-400",
    slate: "ring-2 ring-offset-2 ring-slate-400",
    stone: "ring-2 ring-offset-2 ring-stone-400",
    teal: "ring-2 ring-offset-2 ring-teal-400",
    violet: "ring-2 ring-offset-2 ring-violet-400",
    yellow: "ring-2 ring-offset-2 ring-yellow-400",
    zinc: "ring-2 ring-offset-2 ring-zinc-400",
};

export const avatarBgColor: Record<LwColor, string> = {
    amber: "bg-amber-400",
    blue: "bg-blue-400",
    cyan: "bg-cyan-400",
    emerald: "bg-emerald-400",
    fuchsia: "bg-fuchsia-400",
    gray: "bg-gray-400",
    green: "bg-green-400",
    indigo: "bg-indigo-400",
    lime: "bg-lime-400",
    neutral: "bg-neutral-400",
    orange: "bg-orange-400",
    pink: "bg-pink-400",
    purple: "bg-purple-400",
    red: "bg-red-400",
    rose: "bg-rose-400",
    sky: "bg-sky-400",
    slate: "bg-slate-400",
    stone: "bg-stone-400",
    teal: "bg-teal-400",
    violet: "bg-violet-400",
    yellow: "bg-yellow-400",
    zinc: "bg-zinc-400",
};
