import { LwColor } from "../types";

export const buttonContainedColor: Record<LwColor, string> = {
    amber: "text-white bg-amber-600 hover:bg-amber-500",
    blue: "text-white bg-blue-600 hover:bg-blue-500",
    cyan: "text-white bg-cyan-600 hover:bg-cyan-500",
    emerald: "text-white bg-emerald-600 hover:bg-emerald-500",
    fuchsia: "text-white bg-fuchsia-600 hover:bg-fuchsia-500",
    gray: "text-white bg-gray-600 hover:bg-gray-500",
    green: "text-white bg-green-600 hover:bg-green-500",
    indigo: "text-white bg-indigo-600 hover:bg-indigo-500",
    lime: "text-white bg-lime-600 hover:bg-lime-500",
    neutral: "text-white bg-neutral-600 hover:bg-neutral-500",
    orange: "text-white bg-orange-600 hover:bg-orange-500",
    pink: "text-white bg-pink-600 hover:bg-pink-500",
    purple: "text-white bg-purple-600 hover:bg-purple-500",
    red: "text-white bg-red-600 hover:bg-red-500",
    rose: "text-white bg-rose-600 hover:bg-rose-500",
    sky: "text-white bg-sky-600 hover:bg-sky-500",
    slate: "text-white bg-slate-600 hover:bg-slate-500",
    stone: "text-white bg-stone-600 hover:bg-stone-500",
    teal: "text-white bg-teal-600 hover:bg-teal-500",
    violet: "text-white bg-violet-600 hover:bg-violet-500",
    yellow: "text-white bg-yellow-600 hover:bg-yellow-500",
    zinc: "text-white bg-zinc-600 hover:bg-zinc-500",
};

export const buttonOutlinedColor: Record<LwColor, string> = {
    amber: "text-amber-600 hover:text-white bg-transparent hover:bg-amber-600 border border-amber-600",
    blue: "text-blue-600 hover:text-white bg-transparent hover:bg-blue-600 border border-blue-600",
    cyan: "text-cyan-600 hover:text-white bg-transparent hover:bg-cyan-600 border border-cyan-600",
    emerald:
        "text-emerald-600 hover:text-white bg-transparent hover:bg-emerald-600 border border-emerald-600",
    fuchsia:
        "text-fuchsia-600 hover:text-white bg-transparent hover:bg-fuchsia-600 border border-fuchsia-600",
    gray: "text-gray-600 hover:text-white bg-transparent hover:bg-gray-600 border border-gray-600",
    green: "text-green-600 hover:text-white bg-transparent hover:bg-green-600 border border-green-600",
    indigo: "text-indigo-600 hover:text-white bg-transparent hover:bg-indigo-600 border border-indigo-600",
    lime: "text-lime-600 hover:text-white bg-transparent hover:bg-lime-600 border border-lime-600",
    neutral:
        "text-neutral-600 hover:text-white bg-transparent hover:bg-neutral-600 border border-neutral-600",
    orange: "text-orange-600 hover:text-white bg-transparent hover:bg-orange-600 border border-orange-600",
    pink: "text-pink-600 hover:text-white bg-transparent hover:bg-pink-600 border border-pink-600",
    purple: "text-purple-600 hover:text-white bg-transparent hover:bg-purple-600 border border-purple-600",
    red: "text-red-600 hover:text-white bg-transparent hover:bg-red-600 border border-red-600",
    rose: "text-rose-600 hover:text-white bg-transparent hover:bg-rose-600 border border-rose-600",
    sky: "text-sky-600 hover:text-white bg-transparent hover:bg-sky-600 border border-sky-600",
    slate: "text-slate-600 hover:text-white bg-transparent hover:bg-slate-600 border border-slate-600",
    stone: "text-stone-600 hover:text-white bg-transparent hover:bg-stone-600 border border-stone-600",
    teal: "text-teal-600 hover:text-white bg-transparent hover:bg-teal-600 border border-teal-600",
    violet: "text-violet-600 hover:text-white bg-transparent hover:bg-violet-600 border border-violet-600",
    yellow: "text-yellow-600 hover:text-white bg-transparent hover:bg-yellow-600 border border-yellow-600",
    zinc: "text-zinc-600 hover:text-white bg-transparent hover:bg-zinc-600 border border-zinc-600",
};

export const buttonLightColor: Record<LwColor, string> = {
    amber: "bg-transparent hover:bg-amber-100 text-amber-600",
    blue: "bg-transparent hover:bg-blue-100 text-blue-600",
    cyan: "bg-transparent hover:bg-cyan-100 text-cyan-600",
    emerald: "bg-transparent hover:bg-emerald-100 text-emerald-600",
    fuchsia: "bg-transparent hover:bg-fuchsia-100 text-fuchsia-600",
    gray: "bg-transparent hover:bg-gray-100 text-gray-600",
    green: "bg-transparent hover:bg-green-100 text-green-600",
    indigo: "bg-transparent hover:bg-indigo-100 text-indigo-600",
    lime: "bg-transparent hover:bg-lime-100 text-lime-600",
    neutral: "bg-transparent hover:bg-neutral-100 text-neutral-600",
    orange: "bg-transparent hover:bg-orange-100 text-orange-600",
    pink: "bg-transparent hover:bg-pink-100 text-pink-600",
    purple: "bg-transparent hover:bg-purple-100 text-purple-600",
    red: "bg-transparent hover:bg-red-100 text-red-600",
    rose: "bg-transparent hover:bg-rose-100 text-rose-600",
    sky: "bg-transparent hover:bg-sky-100 text-sky-600",
    slate: "bg-transparent hover:bg-slate-100 text-slate-600",
    stone: "bg-transparent hover:bg-stone-100 text-stone-600",
    teal: "bg-transparent hover:bg-teal-100 text-teal-600",
    violet: "bg-transparent hover:bg-violet-100 text-violet-600",
    yellow: "bg-transparent hover:bg-yellow-100 text-yellow-600",
    zinc: "bg-transparent hover:bg-zinc-100 text-zinc-600",
};
