import { LwColor } from "../types";

export const checkboxColor: Record<LwColor, string> = {
    amber: "bg-amber-600 text-white",
    blue: "bg-blue-600 text-white",
    cyan: "bg-cyan-600 text-white",
    emerald: "bg-emerald-600 text-white",
    fuchsia: "bg-fuchsia-600 text-white",
    gray: "bg-gray-600 text-white",
    green: "bg-green-600 text-white",
    indigo: "bg-indigo-600 text-white",
    lime: "bg-lime-600 text-white",
    neutral: "bg-neutral-600 text-white",
    orange: "bg-orange-600 text-white",
    pink: "bg-pink-600 text-white",
    purple: "bg-purple-600 text-white",
    red: "bg-red-600 text-white",
    rose: "bg-rose-600 text-white",
    sky: "bg-sky-600 text-white",
    slate: "bg-slate-600 text-white",
    stone: "bg-stone-600 text-white",
    teal: "bg-teal-600 text-white",
    violet: "bg-violet-600 text-white",
    yellow: "bg-yellow-600 text-white",
    zinc: "bg-zinc-600 text-white",
};
